apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudfritz
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudfritz
    spec:
      imagePullSecrets:
      - name: gitlab-reg-secret
      containers:
      - name: cloudfritz
        image: registry.gitlab.com/yoyostile/cloudfritz:latest
        imagePullPolicy: Always
