apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudfritz
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudfritz
    spec:
      containers:
      - name: cloudfritz
        image: yoyostile/cloudfritz:latest
        imagePullPolicy: Always
