apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloudfritz-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  tls:
  - secretName: cloudfritz-tls
    hosts:
    - cloudfritz.r4r3.me
  rules:
  - host: cloudfritz.r4r3.me
    http:
      paths:
      - path: /
        backend:
          serviceName: cloudfritz
          servicePort: http
