name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: docker.io
        username: yoyostile
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build the Docker image
      run: |
        docker build . -t yoyostile/cloudfritz:$(date +%s) -t yoyostile/cloudfritz:latest
        docker push yoyostile/cloudfritz:$(date +%s)
        docker push yoyostile/cloudfritz:latest
